### ISSUE TITLE
css file path

### ISSUE THREAD

**Issue by brunosvx** [Callietron300/NFTcard#1]
your correct path to .css file is "style.css" instead of "../style.css" cause it's on the same directory level as index.html

**Comment by Callietron300** [comment]
Thank so much for looking- it doesn't seems to have worked though! :(

**Comment by brunosvx** [comment]
you changed to "/style.css" instead of "style.css"

**Comment by Callietron300** [comment]
Hmm I've tried that and ."/" And neither worked really odd

**Comment by brunosvx** [comment]
your project is right, i tested it on my pc and it worked normally with the same code and files, i have no idea why its not working

**Comment by Callietron300** [comment]
Same here! In the morning I'll try see if Github has any trouble shooting help email or something to get some support. Thank you for trying ☺️

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by brunosvx** [comment]
it's working now https://callietron300.github.io/NFTcard/

**Comment by Callietron300** [comment]
thank you! I fixed the file path issues too for the images, thanks for your help :)
